apiVersion: v1
kind: Service
metadata:
  name: {{ include "foundry-vtt.fullname" . }}
  labels:
    app: {{ .Chart.Name }}
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: {{ .Chart.Name }}
  type: ClusterIP