{{- if .Values.replicationUser }}
{{- if and .Values.replicationUser.sealedUsername .Values.replicationUser.sealedPassword }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  labels:
    pg-cluster: {{ include "postgres.fullname" . }}
  name: {{ include "postgres.fullname" . }}-primaryuser-secret
  namespace: {{ .Values.namespace | quote }}
spec:
  encryptedData:
    password: {{ .Values.replicationUser.sealedPassword }}
    username: {{ .Values.replicationUser.sealedUsername }}
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      labels:
        pg-cluster: {{ include "postgres.fullname" . }}
      name: {{ include "postgres.fullname" . }}-primaryuser-secret
      namespace: {{ .Values.namespace | quote }}
{{- end }}
{{- end }}
