{{- if .Values.tls }}
{{- if .Values.tls.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: {{ include "postgres.fullname" . }}-ca
  namespace: {{ .Values.namespace | quote }}
spec:
  encryptedData:
    ca.cert: {{ required "tls.sealedCa value must be provided if tls.enabled is true" .Values.tls.sealedCa | quote}}
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: {{ include "postgres.fullname" . }}-ca
      namespace: {{ .Values.namespace | quote }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: {{ include "postgres.fullname" . }}-keypair
  namespace: {{ .Values.namespace | quote }}
spec:
  encryptedData:
    tls.crt: {{ required "tls.sealedCrt value must be provided if tls.enabled is true" .Values.tls.sealedCrt | quote}}
    tls.key: {{ required "tls.sealedKey value must be provided if tls.enabled is true" .Values.tls.sealedKey | quote}}
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: {{ include "postgres.fullname" . }}-keypair
      namespace: {{ .Values.namespace | quote }}
    type: kubernetes.io/tls
{{- end }}
{{- end }}
