{{- if .Values.dbUser }}
{{- if and .Values.dbUser.sealedUsername .Values.dbUser.sealedPassword }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  labels:
    pg-cluster: {{ include "postgres.fullname" . }}
  name: {{ include "postgres.fullname" . }}-{{ default (include "postgres.fullname" . ) (default (dict) .Values.dbUser).username }}-secret
  namespace: {{ .Values.namespace | quote }}
spec:
  encryptedData:
    password: {{ .Values.dbUser.sealedPassword }}
    username: {{ .Values.dbUser.sealedUsername }}
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      labels:
        pg-cluster: {{ include "postgres.fullname" . }}
      name: {{ include "postgres.fullname" . }}-{{ default (include "postgres.fullname" . ) (default (dict) .Values.dbUser).username }}-secret
      namespace: {{ .Values.namespace | quote }}
{{- end }}
{{- end }}
