apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    path: traefik
    repoURL: https://github.com/traefik/traefik-helm-chart.git
    targetRevision: v9.13.0
    helm:
      values: |
        image:
          tag: v2.4.0
        ingressClass:
          # something is weird with Helm Capabilities in Argo, so we cannot pass the check for this
          enabled: false
        ingressRoute:
          dashboard:
            enabled: false
        resources:
          limits:
            cpu: "300m"
            memory: "150Mi"

  destination:
    namespace: default
    server: {{ .Values.spec.destination.server }}

  # Sync policy
  syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: -1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m