apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress-jen
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    helm: {}
    path: applications/wordpress-jen
    repoURL: https://github.com/skleinjung/pegasus-deployments.git
    targetRevision: development
