apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`prometheus.dev.pegasus`)
      kind: Rule
      services:
        - name: prometheus
          port: 9090