traefik:
  additionalArguments:
    - --certificatesresolvers.production.acme.caserver="https://acme-v02.api.letsencrypt.org/directory"
    - --certificatesresolvers.production.acme.dnsChallenge.delaybeforecheck=0
    - --certificatesresolvers.production.acme.dnsChallenge.provider=cloudflare
    - --certificatesresolvers.production.acme.email=sean@thrashplay.com
    - --certificatesresolvers.production.acme.storage="/etc/traefik/acme/certs-production.json"
    - --certificatesresolvers.staging.acme.caserver="https://acme-staging-v02.api.letsencrypt.org/directory"
    - --certificatesresolvers.staging.acme.dnsChallenge.delaybeforecheck=0
    - --certificatesresolvers.staging.acme.dnsChallenge.provider=cloudflare
    - --certificatesresolvers.staging.acme.email=sean@thrashplay.com
    - --certificatesresolvers.staging.acme.storage="/etc/traefik/acme/certs-staging.json"
  envFrom:
    - secretRef:
        name: acme-secrets
  image:
    tag: v2.4.0
  ingressClass:
    # something is weird with Helm Capabilities in Argo, so we cannot pass the check for this
    enabled: false
  ingressRoute:
    dashboard:
      enabled: false
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 128Mi
    path: /etc/traefik/acme
  resources:
    limits:
      cpu: "300m"
      memory: "150Mi"