apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-ingresses
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    path: applications/system-ingresses
    repoURL: https://github.com/skleinjung/pegasus-deployments.git
    targetRevision: {{ .Values.spec.source.targetRevision }}

  destination:
    namespace: default
    server: {{ .Values.spec.destination.server }}
