apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: jen-web-wordpress
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`{{ .Values.hostname }}`)
      services:
        - name: jen-web-wordpress
          port: 80
  tls:
    certResolver: production
    options: {}

