apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: jen-web-mariadb-db-secret
  namespace: default
spec:
  encryptedData:
    mariadb-password: {{ .Values.encryptedMariaDbPassword | quote }}
    mariadb-replication-password: {{ .Values.encryptedMariaDbReplicationPassword | quote }}
    mariadb-root-password: {{ .Values.encryptedMariaDbRootPassword | quote }}
  template:
    metadata:
      name: jen-web-mariadb-db-secret
      namespace: default

