apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: jen-web-wordpress-secret
  namespace: default
spec:
  encryptedData:
    wordpress-password: {{ .Values.wordpressPassword }}
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: jen-web-wordpress-secret
      namespace: default

