apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: jen-web-wordpress-db-secret
  namespace: default
spec:
  encryptedData:
    WORDPRESS_DATABASE_PASSWORD: {{ .Values.encryptedMariaDbPassword | quote }}
  template:
    metadata:
      name: jen-web-wordpress-db-secret
      namespace: default

