apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: metallb-system

bases:
- ../base

configMapGenerator:
- name: config
  files:
  - config=config.yaml
  options:
    disableNameSuffixHash: true