config:
  archive_mode: "true"
  archive_timeout: "60"
  backrest_aws_s3_bucket: ""
  backrest_aws_s3_endpoint: ""
  backrest_aws_s3_key: ""
  backrest_aws_s3_region: ""
  backrest_aws_s3_secret: ""
  backrest_aws_s3_uri_style: ""
  backrest_aws_s3_verify_tls: "true"
  backrest_port: "2022"
  badger: "false"
  ccp_image_prefix: "registry.developers.crunchydata.com/crunchydata"
  ccp_image_pull_secret: ""
  ccp_image_pull_secret_manifest: ""
  ccp_image_tag: "centos8-13.1-4.6.0"
  create_rbac: "true"
  crunchy_debug: "false"
  db_name: ""
  db_password_age_days: "0"
  db_password_length: "24"
  db_port: "5432"
  db_replicas: "0"
  db_user: "pgodefault"
  default_instance_memory: "128Mi"
  default_pgbackrest_memory: "48Mi"
  default_pgbouncer_memory: "24Mi"
  default_exporter_memory: "24Mi"
  delete_operator_namespace: "false"
  delete_watched_namespaces: "false"
  disable_auto_failover: "false"
  disable_fsgroup: "false"
  reconcile_rbac: "true"
  exporterport: "9187"
  metrics: "true"
  namespace: "default"
  namespace_mode: "dynamic"
  pgbadgerport: "10000"
  pgo_add_os_ca_store: "false"
  pgo_admin_password: ""
  pgo_admin_perms: "*"
  pgo_admin_role_name: "pgoadmin"
  pgo_admin_username: "admin"
  pgo_apiserver_port: "8443"
  pgo_apiserver_url: "https://postgres-operator"
  pgo_client_cert_secret: "pgo.tls"
  pgo_client_container_install: "true"
  pgo_client_install: "true"
  pgo_client_version: "4.6.0"
  pgo_cluster_admin: "false"
  pgo_disable_eventing: "false"
  pgo_disable_tls: "false"
  pgo_image_prefix: "registry.developers.crunchydata.com/crunchydata"
  pgo_image_pull_secret: ""
  pgo_image_pull_secret_manifest: ""
  pgo_image_tag: "centos8-4.6.0"
  pgo_installation_name: "main"
  pgo_noauth_routes: ""
  pgo_operator_namespace: "pgo"
  pgo_tls_ca_store: ""
  pgo_tls_no_verify: "false"
  pod_anti_affinity: "preferred"
  pod_anti_affinity_pgbackrest: ""
  pod_anti_affinity_pgbouncer: ""
  scheduler_timeout: "3600"
  service_type: "ClusterIP"
  sync_replication: "false"
  backrest_storage: "localstorage"
  backup_storage: "localstorage"
  primary_storage: "localstorage"
  replica_storage: "localstorage"
  wal_storage: ""
  storage1_access_mode: "ReadWriteOnce"
  storage1_class: "local-path"
  storage1_name: "localstorage"
  storage1_size: "1G"
  storage1_type: "dynamic"
  storage2_access_mode: "ReadWriteMany"
  storage2_class: "nfs"
  storage2_name: "nfsstorage"
  storage2_size: "1G"
  storage2_supplemental_groups: "65534"
  storage2_type: "dynamic"
