apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: metallb-system

resources:
- namespace.yaml
- memberlist-secret.yaml
- metallb-v0.9.5.yaml

configMapGenerator:
- name: config
  files:
  - config=config.yaml
  options:
    disableNameSuffixHash: true