kind: Service
apiVersion: v1
metadata:
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/name: traefik
  name: traefik-metrics
  namespace: traefik
spec:
  ports:
    - name: metrics
      protocol: TCP
      port: 9001
      targetPort: 9001
  selector:
    app.kubernetes.io/instance: traefik
    app.kubernetes.io/name: traefik
  type: ClusterIP
