apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: basic-auth
  namespace: openfaas
spec:
  encryptedData:
    basic-auth-password: AgA7HlrrElLQMrh8I1480z2FeJAKJmSTjhS8H5UIdgCpkO7AD6aL0JwPQdcP8hVsErVcii/4qconfeffNDhaEa32EQVfczrr96TgOxKSvLQGxszIeAzYIpFwigehT6u8rk0QIucQhJtzVS+s05O0bFBQ1lSciyvt37oCvyRdFffesEZ/xZbDoAqnhaKAOvwL7dK5ymcl7y9Rh3ggUDZZ7Cdw5zLpDsc0QUECG13P1PMx8IpmtycG2Y+KG1X0O9Mm3O1hBkB+RuIFwiU2GdLCX8MTp/5x99bj+KIHpVsPhkrAQQWvNpHDOBGuRQ8PIKMLRtE6TidojVZqu93safiYqoM12onWhVTYAcH0HuJzmCVp2NGPslykL3ZOUh36qeCLGWiiE4+0NONKWY56mMepXkWXfPzRJ6egYaRY635OZj3TwqTgPHhH/1CahSo+AjehQM/tNhWfi24uDNA02DxwU/L+Q3GMlvK6yYJoOnHxAoolKBf598HHM2XFis9WzwGJrRZtgQJ8vBvmoGTLsujpcpqnLdOsXcwc1Lf4qeDA4XOj/R6R8vPZoEzOwI9fzp+0CqG8uL2X+WvT/5TSJHxIiVX+Z1ZA/H+ap4fn94DWaO5YPd+zrr8PknFLza2M12ncAVo2JMUuyC3yfbQpb6AGiEYLz47SG1cfU3W6bNxT50mOE81bBqBKCpssCp3BZEFYUqi+OUVRXkQQHjekk5cNvUnC1FIl7fJlQIbBqMDkUSrX
    basic-auth-user: AgCC1/ahxpXuEEG+meyPfKOkf8s5FSRNKbC++lNPAiQzI1vAJUkfAJnFQY9+NczBnctKEB38/E2eWcb0byg0ZlmhfGhx9Jd4mZXVXfk/GDeJy6UDIz8lNTTwoyJmvqcGH7AqQTifAwh6eZsiT+aF/4XNWFMHeAyQtSEpwXQ6cxOAyVHQlMUPRq0ybGfycPND5U+HhksS7OPuWswz4gw6afEZWClsao5MVy+1+zNM2xGxLuzpLLOkfYK39yYWaNuG5lHT29UBxiyLuyoXScq5moZu+VNSUAQ12D1XVJPX9vXZPy/RGdlffzyr1LHe41ehVHoCSK7KUopGuHnzTATg2kSA5fk7rpdPrlbGfZ1edkjDcsqzMEbGZbyiTcOf7nmNbYkt60z/MZAxfEY1glJcUayXaFV5rDFFP2sLz7vn48bsWEm5EP98vlhbBHgt9ULx1lzK6y4ZS8Uz3tHl2sxlhJCSPXFZOeRKj3AmwuLsQjW4JCCS4cTT4IPeaksbU+LWkPR9tB6dMyVrsjla5vpmPkrQdNK0Fb9+8yi4z/z5yJZqyv8HPMZduiohHYL7U4ihDeso7GUVWGHUasW/cCZtVW5l7MOX57ldoVVqfwCraWjJtN3UzOzpYsxDfAcMJhgm/plKwSA7JZc+gJRnWTHu3ujMuoe1xzXdlaKJ2CdaMJ3u+KK6R9j1OtaEeHDALlfmCZWnWvN0DQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: basic-auth
      namespace: openfaas