apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: {{ .Values.grafana.adminPassword }}
    admin-user: {{ .Values.grafana.adminUser }}
  template:
    metadata:
      name: grafana-credentials
      namespace: monitoring

