
mariadb:
  auth:
    database: jenwp
    existingSecret: jen-web-mariadb-db-secret
    username: jenwp-a
  image:
    debug: false
  metrics:
    enabled: true
    serviceMonitor:
      additionalLabels:
        release: kube-prometheus
      enabled: true
  primary:
    configuration: |-
      [mysqld]
      basedir=/opt/bitnami/mariadb
      bind-address=0.0.0.0
      character-set-server=UTF8
      collation-server=utf8_general_ci
      explicit_defaults_for_timestamp
      log-error=/opt/bitnami/mariadb/logs/mysqld.log
      max_allowed_packet=16M
      # this is needed to run in memory-limited environments
      performance_schema=off
      pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
      plugin_dir=/opt/bitnami/mariadb/plugin
      port=3306
      skip-name-resolve
      socket=/opt/bitnami/mariadb/tmp/mysql.sock
      tmpdir=/opt/bitnami/mariadb/tmp

      [client]
      default-character-set=UTF8
      plugin_dir=/opt/bitnami/mariadb/plugin
      port=3306
      socket=/opt/bitnami/mariadb/tmp/mysql.sock

      [manager]
      pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
      port=3306
      socket=/opt/bitnami/mariadb/tmp/mysql.sock
    persistence:
      enabled: true
    resources:
      limits:
        memory: 1024Mi
      requests:
        cpu: 250m
        memory: 512Mi

wordpress:
  allowEmptyPassword: false
  externalDatabase:
    database: jenwp
    existingSecret: jen-web-mariadb-db-secret
    host: jen-web-mariadb
    user: jenwp-a
  image:
    debug: true
  ingress:
    enabled: false
  livenessProbe:
    httpGet:
      httpHeaders:
        - name: X-Forwarded-Proto
          value: https
      port: https
      scheme: HTTPS
  mariadb:
    enabled: false
  persistence:
    enabled: true
  readinessProbe:
    httpGet:
      httpHeaders:
        - name: X-Forwarded-Proto
          value: https
      port: https
      scheme: HTTPS
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  service:
    type: ClusterIP
  wordpressScheme: https
  wordpressSkipInstall: true
  