hostname: jenniferkleinjung.com
wordpress:
  ingress.hostname: jenniferkleinjung.com
  livenessProbe:
    enabled: true
    httpGet:
      path: /wp-admin/install.php
      port: http
      scheme: HTTP
      ## If using an HTTPS-terminating load-balancer, the probes may need to behave
      ## like the balancer to prevent HTTP 302 responses. According to the Kubernetes
      ## docs, 302 should be considered "successful", but this issue on GitHub
      ## (https://github.com/kubernetes/kubernetes/issues/47893) shows that it isn't.
      ##
      httpHeaders:
      - name: X-Forwarded-Proto
        value: https
    initialDelaySeconds: 360
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  persistence:
    enabled: true
    accessMode: ReadWriteMany
    size: 100Gi
  readinessProbe:
    enabled: true
    httpGet:
      path: /wp-login.php
      port: http
      scheme: HTTP
      ## If using an HTTPS-terminating load-balancer, the probes may need to behave
      ## like the balancer to prevent HTTP 302 responses. According to the Kubernetes
      ## docs, 302 should be considered "successful", but this issue on GitHub
      ## (https://github.com/kubernetes/kubernetes/issues/47893) shows that it isn't.
      ##
      httpHeaders:
      - name: X-Forwarded-Proto
        value: https
    initialDelaySeconds: 90
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  service:
    type: ClusterIP
  wordpressBlogName: "Jen's Wordpress Site"
  wordpressEmail: jenniferlkleinjung@gmail.com
  wordpressFirstName: Jennifer
  wordpressLastName: Kleinjung
  wordpressScheme: http
  wordpressUsername: jen
  