hostname: jenniferkleinjung.com
wordpress:
  ingress.hostname: jenniferkleinjung.com
  persistence:
    enabled: true
    accessMode: ReadWriteMany
    size: 100Gi
  service:
    type: ClusterIP
  wordpressBlogName: "Jen's Wordpress Site"
  wordpressEmail: jenniferlkleinjung@gmail.com
  wordpressFirstName: Jennifer
  wordpressLastName: Kleinjung
  wordpressScheme: http
  wordpressUsername: jen
  